USE [DB_DOAN_QLHS]
GO

/****** Object:  Table [dbo].[AccountManage]    Script Date: 12/10/2017 10:06:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AccountManage](
	[username] [varchar](10) NOT NULL,
	[password] [varchar](10) NOT NULL,
	[privilege] [varchar](10) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [DB_DOAN_QLHS]
GO

/****** Object:  Table [dbo].[BANG_DIEM_HS]    Script Date: 12/10/2017 10:06:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BANG_DIEM_HS](
	[MaHocSinh] [nvarchar](10) NOT NULL,
	[MaLop] [nvarchar](10) NOT NULL,
	[MaBangDiem] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_BANG_DIEM_HS] PRIMARY KEY CLUSTERED 
(
	[MaBangDiem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[BANG_DIEM_HS]  WITH CHECK ADD  CONSTRAINT [FK_BANG_DIEM_HS_DANHSACH_HS] FOREIGN KEY([MaHocSinh])
REFERENCES [dbo].[DANHSACH_HS] ([MaHocSinh])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[BANG_DIEM_HS] CHECK CONSTRAINT [FK_BANG_DIEM_HS_DANHSACH_HS]
GO

ALTER TABLE [dbo].[BANG_DIEM_HS]  WITH CHECK ADD  CONSTRAINT [FK_BANG_DIEM_HS_LOP] FOREIGN KEY([MaLop])
REFERENCES [dbo].[LOP] ([MaLop])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[BANG_DIEM_HS] CHECK CONSTRAINT [FK_BANG_DIEM_HS_LOP]
GO


USE [DB_DOAN_QLHS]
GO

/****** Object:  Table [dbo].[CT_BANGDIEM]    Script Date: 12/10/2017 10:06:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CT_BANGDIEM](
	[MaBangDiem] [int] NOT NULL,
	[MaMonHoc] [nvarchar](10) NOT NULL,
	[MANH] [varchar](10) NOT NULL,
	[MaHocKy] [nvarchar](10) NOT NULL,
	[MaLoaiKiemTra] [nvarchar](10) NOT NULL,
	[Diem] [float] NULL,
 CONSTRAINT [PK_CT_BANGDIEM] PRIMARY KEY CLUSTERED 
(
	[MaBangDiem] ASC,
	[MaMonHoc] ASC,
	[MANH] ASC,
	[MaHocKy] ASC,
	[MaLoaiKiemTra] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CT_BANGDIEM]  WITH CHECK ADD  CONSTRAINT [FK_CT_BANGDIEM_BANG_DIEM_HS] FOREIGN KEY([MaBangDiem])
REFERENCES [dbo].[BANG_DIEM_HS] ([MaBangDiem])
GO

ALTER TABLE [dbo].[CT_BANGDIEM] CHECK CONSTRAINT [FK_CT_BANGDIEM_BANG_DIEM_HS]
GO

ALTER TABLE [dbo].[CT_BANGDIEM]  WITH CHECK ADD  CONSTRAINT [FK_CT_BANGDIEM_HOCKY] FOREIGN KEY([MaHocKy])
REFERENCES [dbo].[HOCKY] ([MaHocKy])
GO

ALTER TABLE [dbo].[CT_BANGDIEM] CHECK CONSTRAINT [FK_CT_BANGDIEM_HOCKY]
GO

ALTER TABLE [dbo].[CT_BANGDIEM]  WITH CHECK ADD  CONSTRAINT [FK_CT_BANGDIEM_LOAIKIEMTRA] FOREIGN KEY([MaLoaiKiemTra])
REFERENCES [dbo].[LOAIKIEMTRA] ([MaLoaiKiemTra])
GO

ALTER TABLE [dbo].[CT_BANGDIEM] CHECK CONSTRAINT [FK_CT_BANGDIEM_LOAIKIEMTRA]
GO

ALTER TABLE [dbo].[CT_BANGDIEM]  WITH CHECK ADD  CONSTRAINT [FK_CT_BANGDIEM_MONHOC] FOREIGN KEY([MaMonHoc])
REFERENCES [dbo].[MONHOC] ([MaMonHoc])
GO

ALTER TABLE [dbo].[CT_BANGDIEM] CHECK CONSTRAINT [FK_CT_BANGDIEM_MONHOC]
GO

ALTER TABLE [dbo].[CT_BANGDIEM]  WITH CHECK ADD  CONSTRAINT [FK_CT_BANGDIEM_NAMHOC] FOREIGN KEY([MANH])
REFERENCES [dbo].[NAMHOC] ([MANH])
GO

ALTER TABLE [dbo].[CT_BANGDIEM] CHECK CONSTRAINT [FK_CT_BANGDIEM_NAMHOC]
GO


USE [DB_DOAN_QLHS]
GO

/****** Object:  Table [dbo].[DANHSACH_HS]    Script Date: 12/10/2017 10:07:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DANHSACH_HS](
	[MaHocSinh] [nvarchar](10) NOT NULL,
	[MANH] [nvarchar](10) NOT NULL,
	[HoTen] [nvarchar](50) NOT NULL,
	[GioiTinh] [nvarchar](10) NOT NULL,
	[NgaySinh] [date] NOT NULL,
	[DiaChi] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DANHSACH_HS] PRIMARY KEY CLUSTERED 
(
	[MaHocSinh] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [DB_DOAN_QLHS]
GO

/****** Object:  Table [dbo].[HOCKY]    Script Date: 12/10/2017 10:07:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HOCKY](
	[MaHocKy] [nvarchar](10) NOT NULL,
	[TenHocKy] [nvarchar](50) NULL,
 CONSTRAINT [PK_HOCKY] PRIMARY KEY CLUSTERED 
(
	[MaHocKy] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [DB_DOAN_QLHS]
GO

/****** Object:  Table [dbo].[KHOI]    Script Date: 12/10/2017 10:07:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KHOI](
	[MaKhoi] [nvarchar](10) NOT NULL,
	[TenKhoi] [nvarchar](50) NULL,
	[SoLopToiDa] [int] NULL,
 CONSTRAINT [PK_KHOI] PRIMARY KEY CLUSTERED 
(
	[MaKhoi] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [DB_DOAN_QLHS]
GO

/****** Object:  Table [dbo].[LOAIKIEMTRA]    Script Date: 12/10/2017 10:07:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LOAIKIEMTRA](
	[MaLoaiKiemTra] [nvarchar](10) NOT NULL,
	[TenLoaiKiemTra] [nvarchar](50) NULL,
 CONSTRAINT [PK_LOAIKIEMTRA] PRIMARY KEY CLUSTERED 
(
	[MaLoaiKiemTra] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [DB_DOAN_QLHS]
GO

/****** Object:  Table [dbo].[LOP]    Script Date: 12/10/2017 10:07:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LOP](
	[MaLop] [nvarchar](10) NOT NULL,
	[MaKhoi] [nvarchar](10) NOT NULL,
	[TenLop] [nvarchar](50) NOT NULL,
	[SiSo] [int] NULL,
 CONSTRAINT [PK_LOP] PRIMARY KEY CLUSTERED 
(
	[MaLop] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[LOP]  WITH CHECK ADD  CONSTRAINT [FK_LOP_KHOI] FOREIGN KEY([MaKhoi])
REFERENCES [dbo].[KHOI] ([MaKhoi])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[LOP] CHECK CONSTRAINT [FK_LOP_KHOI]
GO


USE [DB_DOAN_QLHS]
GO

/****** Object:  Table [dbo].[MONHOC]    Script Date: 12/10/2017 10:07:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MONHOC](
	[MaMonHoc] [nvarchar](10) NOT NULL,
	[TenMonHoc] [nvarchar](50) NULL,
 CONSTRAINT [PK_MONHOC] PRIMARY KEY CLUSTERED 
(
	[MaMonHoc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [DB_DOAN_QLHS]
GO

/****** Object:  Table [dbo].[NAMHOC]    Script Date: 12/10/2017 10:08:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[NAMHOC](
	[MANH] [varchar](10) NOT NULL,
	[TENNH] [nvarchar](50) NULL,
	[YNGHIA] [nvarchar](50) NULL,
 CONSTRAINT [PK_NAMHOC_1] PRIMARY KEY CLUSTERED 
(
	[MANH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [DB_DOAN_QLHS]
GO

/****** Object:  Table [dbo].[QUYDINH]    Script Date: 12/10/2017 10:08:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[QUYDINH](
	[MaQuyDinh] [nvarchar](10) NOT NULL,
	[TenQuyDinh] [nvarchar](50) NULL,
	[ThongSo] [int] NULL,
 CONSTRAINT [PK_TIEUCHI] PRIMARY KEY CLUSTERED 
(
	[MaQuyDinh] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [DB_DOAN_QLHS]
GO

/****** Object:  Table [dbo].[TIEPNHAN_HS]    Script Date: 12/10/2017 10:08:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TIEPNHAN_HS](
	[MaHocSinh] [varchar](10) NOT NULL,
	[MANH] [varchar](10) NOT NULL,
	[MaKhoi] [nvarchar](10) NOT NULL,
	[HoTen] [nvarchar](50) NOT NULL,
	[GioiTinh] [nvarchar](10) NOT NULL,
	[NgaySinh] [date] NOT NULL,
	[DiaChi] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TIEPNHAN_HS] PRIMARY KEY CLUSTERED 
(
	[MaHocSinh] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TIEPNHAN_HS]  WITH CHECK ADD  CONSTRAINT [FK_TIEPNHAN_HS_NAMHOC] FOREIGN KEY([MANH])
REFERENCES [dbo].[NAMHOC] ([MANH])
GO

ALTER TABLE [dbo].[TIEPNHAN_HS] CHECK CONSTRAINT [FK_TIEPNHAN_HS_NAMHOC]
GO


